### ISSUE TITLE
Report the number of hops 

### ISSUE THREAD

**Issue by romain-fontugne** [romain-fontugne/ashash#1]
For each dependencies we want to know if the AS is 1, or 2, or 3.... hops away

**Comment by Yh010** [comment]
As per me, resolving this issue involves the following steps:
1)identifying the dependencies
2)Obtaining the IP addresses of each dependency using tools like nslooup or maybe ping
3)using bgpview.io to obtain the AS number for each IP address and storing these in a file

We can probably use the AS number info to identify potential issues related to network latency🤔

**Comment by romain-fontugne** [comment]
ah sorry this is an old issue, we are actually not using this code anymore, I'll close this
